/*
 * eisenstein.c — Scalar reference implementation
 *
 * Clean, readable C11. Works everywhere. This is the ground truth
 * that all vectorized implementations must match exactly.
 */

#include "eisenstein.h"
#include <string.h>

/* === Arithmetic === */

E12 e12_add(E12 x, E12 y) {
    return (E12){ x.a + y.a, x.b + y.b };
}

E12 e12_sub(E12 x, E12 y) {
    return (E12){ x.a - y.a, x.b - y.b };
}

E12 e12_mul(E12 x, E12 y) {
    /* (a₁+b₁ω)(a₂+b₂ω) = a₁a₂ + (a₁b₂+a₂b₁)ω + b₁b₂ω²
     * ω² = -1-ω, so b₁b₂ω² = -b₁b₂ - b₁b₂ω
     * Result: (a₁a₂ - b₁b₂) + (a₁b₂ + a₂b₁ - b₁b₂)ω */
    int32_t aa = x.a * y.a;
    int32_t bb = x.b * y.b;
    int32_t cross = x.a * y.b + y.a * x.b;
    return (E12){ aa - bb, cross - bb };
}

E12 e12_conjugate(E12 x) {
    /* Conjugate of a+bω: a+bω̄ = a+b(-1-ω) = (a-b) + (-b)ω */
    /* Check: x·conj(x) = N(x) via multiply: */
    /* (a+bω)((a-b)-bω) = a(a-b) - b(-b) + [a(-b) + (a-b)b - b(-b)]ω */
    /* = a²-ab+b² + [-ab+ab-b²+b²]ω = (a²-ab+b²) + 0ω = N(x) ✓ */
    return (E12){ x.a - x.b, -x.b };
}

E12 e12_negate(E12 x) {
    return (E12){ -x.a, -x.b };
}

E12 e12_rotate(E12 x, int steps) {
    /* ω·(a+bω) = aω + bω² = aω + b(-1-ω) = -b + (a-b)ω */
    steps = ((steps % 6) + 6) % 6;  /* normalize to [0,5] */
    for (int i = 0; i < steps; i++) {
        int32_t new_a = -x.b;
        int32_t new_b = x.a - x.b;
        x.a = new_a;
        x.b = new_b;
    }
    return x;
}

/* === Norm === */

int32_t e12_norm(E12 x) {
    /* N(a+bω) = a² - ab + b² = (a - b/2)² + 3b²/4, always ≥ 0 */
    return x.a * x.a - x.a * x.b + x.b * x.b;
}

bool e12_in_disk(E12 x, int32_t r) {
    return e12_norm(x) <= r * r;
}

bool e12_eq(E12 x, E12 y) {
    return x.a == y.a && x.b == y.b;
}

/* === Units === */

E12 e12_unit(int k) {
    /* The 6 units of norm 1 in Z[ω]: generated by powers of ω and negation.
     * ±1, ±ω, ±ω²  where ω² = -1-ω.
     * k mod 12 gives 12 directions (6 rotations × 2 signs). */
    k = ((k % 12) + 12) % 12;
    int sign = (k < 6) ? 1 : -1;
    int rot = k % 6;
    E12 base = { 1, 0 };
    E12 rotated = e12_rotate(base, rot);
    return (E12){ rotated.a * sign, rotated.b * sign };
}

/* === Constraint Checking (scalar) === */

int e12_check_constraints_i8(const int8_t* values, const Bound8* bounds,
                              int n, uint64_t* violation_mask) {
    int count = 0;
    uint64_t mask = 0;
    int limit = n > 64 ? 64 : n;
    for (int i = 0; i < limit; i++) {
        if (values[i] < bounds[i].lo || values[i] > bounds[i].hi) {
            mask |= (1ULL << i);
            count++;
        }
    }
    /* Handle remaining elements beyond 64 */
    for (int i = 64; i < n; i++) {
        if (values[i] < bounds[i].lo || values[i] > bounds[i].hi) {
            count++;
        }
    }
    if (violation_mask) *violation_mask = mask;
    return count;
}

int e12_check_constraints_i16(const int16_t* values, const Bound16* bounds,
                               int n, uint64_t* violation_mask) {
    int count = 0;
    uint64_t mask = 0;
    int limit = n > 64 ? 64 : n;
    for (int i = 0; i < limit; i++) {
        if (values[i] < bounds[i].lo || values[i] > bounds[i].hi) {
            mask |= (1ULL << i);
            count++;
        }
    }
    for (int i = 64; i < n; i++) {
        if (values[i] < bounds[i].lo || values[i] > bounds[i].hi) {
            count++;
        }
    }
    if (violation_mask) *violation_mask = mask;
    return count;
}

int e12_check_constraints_i32(const int32_t* values, const int32_t* lo,
                               const int32_t* hi, int n, uint64_t* violation_mask) {
    int count = 0;
    uint64_t mask = 0;
    int limit = n > 64 ? 64 : n;
    for (int i = 0; i < limit; i++) {
        if (values[i] < lo[i] || values[i] > hi[i]) {
            mask |= (1ULL << i);
            count++;
        }
    }
    for (int i = 64; i < n; i++) {
        if (values[i] < lo[i] || values[i] > hi[i]) {
            count++;
        }
    }
    if (violation_mask) *violation_mask = mask;
    return count;
}

/* === Batch Operations (scalar fallback) === */

void e12_norm_batch(const E12* xs, int32_t* norms, int n) {
    for (int i = 0; i < n; i++) {
        norms[i] = e12_norm(xs[i]);
    }
}

void e12_check_batch_i8(const int8_t* vals, const Bound8* bounds,
                         int n, uint8_t* results) {
    for (int i = 0; i < n; i++) {
        results[i] = (vals[i] < bounds[i].lo || vals[i] > bounds[i].hi) ? 1 : 0;
    }
}
